require("user")
require("config.options")
require("config.autocmds")
spec ("user.themes.rosepine")
spec ("user.treesitter")
spec ("user.treesitter-textobjects")
spec ("user.which-key")
spec ("user.telescope")
spec ("user.lspconfig")
spec ("user.blink")
spec ("user.lazydev")
spec ("user.nvim-dap")
spec ("user.nvim-dap-vt")
spec ("user.nvim-dap-ui")
spec ("user.oil")
spec ("user.autopairs")
spec ("user.neorg")
spec ("user.lualine")
spec ("user.surround")
require("user.lazy")

