require("user")
require("config.options")
require("config.autocmds")
spec ("user.colorscheme")
spec ("user.treesitter")
spec ("user.treesitter-textobjects")
spec ("user.which-key")
spec ("user.telescope")
spec ("user.lspconfig")
spec ("user.blink")
spec ("user.lazydev")
spec ("user.nvim-dap")
spec ("user.nvim-dap-vt")
spec ("user.nvim-dap-ui")
spec ("user.oil")
require("user.lazy")

